### ISSUE TITLE
Respond to size constraints 

### ISSUE THREAD

**Issue by scniro** [scniro/react-codemirror2#58]
`width: 100% height: 100%` is nearly impossible to get working, especially with flexbox in the mix. Can we find a way to be more responsive with sizing?

**Comment by scniro** [comment]
@contra @veggiemonk so this lib indeed passes through the [user defined class](https://github.com/scniro/react-codemirror2/blob/master/src/index.tsx#L769) and doesn't ship with any hardcoded styles to it (`.react-codemirror2` is applied to the component but is empty).

I played with this a bit and the following seemed to work for me. Can you try out and let me know if this works? I would absolutely love an isolated use case that clearly demonstrates this shortcoming. Please share one if you can? I'm trying to figure out what can be done on my end that applying styles in implementation can't achieve. 

```css
.react-codemirror2 {
  flex: 1 1 auto;
  margin-top: 0;
  height: 100%;
  position: relative;
}

.CodeMirror {
  position:absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  height: 100%;
}
```

**Comment by veggiemonk** [comment]
Hi  @scniro,

Thanks for getting in touch. 
I just quickly tried it out and it looks good.
So far, it seems to be good enough for my simple use case but I'll try to customize it further and give feedback here. To give it a specific doesn't seem trivial. I'll let you know.
 
 Thank you. 👍

**Comment by scniro** [comment]
Going to close this out for now as I have't had any further breakthroughs on this and the above styling seems to work. Please reopen if you have any other difficulty with this!

**Comment by contra** [comment]
@scniro Thanks, sorry for no response I haven't had time to confirm that fixes as we had switched editors already.

**Comment by sherry0429** [comment]
meet same questions here,
reason is that 
<.codemirror2> can not set 'style' flag. code like this is useless:

```javascript
import {UnControlled as CodeMirror} from 'react-codemirror2';
<CodeMirror>
style=...
...
</CodeMirror>

So, when try to set real codemirror height & width to 100%, it will useless because of it's parent node 'react-codemirror2' have not a certain height & width.

Hope this could support style flags. thanks.
```

**Comment by FiV0** [comment]
Just in case anyone runs across this. I had to add `!important` to the `height` attribute.
```css
.CodeMirror {
  position:absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  height: 100% !important;
}
```
